#!/bin/sh

sdk_install_dir="@EMLINUX_SDK_INSTALL_DIR@"

SDK_USR_BIN="${sdk_install_dir}/usr/bin"

export PATH="${SDK_USR_BIN}:${PATH}"

export CC="${SDK_USR_BIN}/@EMLINUX_SDK_ARCH@-linux-gnu-gcc"
export CXX="${SDK_USR_BIN}/@EMLINUX_SDK_ARCH@-linux-gnu-g++"
export CPP="${SDK_USR_BIN}/@EMLINUX_SDK_ARCH@-linux-gnu-cpp"
export AS="${SDK_USR_BIN}/@EMLINUX_SDK_ARCH@-linux-gnu-as"
export LD="${SDK_USR_BIN}/@EMLINUX_SDK_ARCH@-linux-gnu-ld$"
export STRIP="${SDK_USR_BIN}/@EMLINUX_SDK_ARCH@-linux-gnu-strip"
export RANLIB="${SDK_USR_BIN}/@EMLINUX_SDK_ARCH@-linux-gnu-ranlib"
export OBJCOPY="${SDK_USR_BIN}/@EMLINUX_SDK_ARCH@-linux-gnu-objcopy"
export OBJDUMP="${SDK_USR_BIN}/@EMLINUX_SDK_ARCH@-linux-gnu-objdump"
export AR="${SDK_USR_BIN}/@EMLINUX_SDK_ARCH@-linux-gnu-ar"
export NM="${SDK_USR_BIN}/@EMLINUX_SDK_ARCH@-linux-gnu-nm"
