BBMULTICONFIG = " \
  qemu-arm64-bookworm \
  qemu-arm-bookworm \
  qemu-amd64-bookworm \
  generic-x86-64-bookworm \
  raspberrypi3bplus-64-bookworm \
  raspberrypi4b-64-bookworm \
  qemu-arm64-trixie \
  qemu-arm-trixie \
  qemu-amd64-trixie \
  generic-x86-64-trixie \
  raspberrypi4b-64-trixie \
"
