#
# EMLinux profile
#
# Copyright (c) Cybertrust Japan Co., Ltd.
#
# SPDX-License-Identifier: MIT
#

require conf/distro/debian-trixie.conf
require emlinux-common.inc

HOST_DISTRO="emlinux-trixie"

PREFERRED_VERSION_linux-cip ?= "6.12.%"

DISTRO_CONFIG_SCRIPT = "${LAYERDIR_emlinux}/conf/distro/emlinux-configscript.sh"

DISTRO_APT_SOURCES = "conf/distro/emlinux-trixie.list"
