require include/emlinux.inc

DISTRO = "emlinux"

LINUX_GIT_BRANCH ?= "linux-4.19.y-cip"
LINUX_GIT_SRCREV ?= "4bc566200edfd8e9dc784404bc3a51aa156677d5"
LINUX_CVE_VERSION ??= "4.19.323
"
LINUX_CIP_VERSION ??= "v4.19.323-cip114"
#
# If you want to use latest revision of the kernel, append the following line
# to local.conf
#
#LINUX_GIT_SRCREV = "${LINUX_GIT_BRANCH}"

# preferred providers and versions
require conf/distro/include/emlinux-preferred-provider.inc
